import { type Commit } from '../commit';
import { type ResolvedArtifactId } from '../resolved-artifact-id';
import { type MergePole } from './merge-poles';

// Unfortunately, there is no definitive list for these conflict types.
// The list was generated by an LLM and cross-checked with Git's source file:
// https://github.com/git/git/blob/9a2fb147f2c61d0cab52c883e7e26f5b7948e3ed/merge-ort.c

// Both poles modified the same file in conflicting ways.
export type ContentConflict = {
  kind: 'content';
  sourceArtifactId: ResolvedArtifactId;
  targetArtifactId: ResolvedArtifactId;
  commonAncestorArtifactId: ResolvedArtifactId;
  path: string;
};

export const isContentConflict = (
  conflict: MergeConflict
): conflict is ContentConflict => conflict.kind === 'content';

// One pole deleted a file while the other modified it.
export type ModifyDeleteConflict = {
  kind: 'modify/delete';
  artifactId: ResolvedArtifactId;
  path: string;
  deletedIn: MergePole;
};

export const isModifyDeleteConflict = (
  conflict: MergeConflict
): conflict is ModifyDeleteConflict => conflict.kind === 'modify/delete';

// Both poles added a file with the same name but different content.
export type AddAddConflict = {
  kind: 'add/add';
  sourceArtifactId: ResolvedArtifactId;
  targetArtifactId: ResolvedArtifactId;
  path: string;
};

export const isAddAddConflict = (
  conflict: MergeConflict
): conflict is AddAddConflict => conflict.kind === 'add/add';

// One pole added a file while the other added a directory with the same name.
export type FileDirectoryConflict = {
  kind: 'file/directory';
  filePath: string;
  directoryPath: string;
};

export const isFileDirectoryConflict = (
  conflict: MergeConflict
): conflict is FileDirectoryConflict => conflict.kind === 'file/directory';

// Both poles renamed the same file to different names.
export type RenameRenameConflict = {
  kind: 'rename/rename';
  artifactId: ResolvedArtifactId;
  basePath: string;
  targetPath: string;
  sourcePath: string;
};

export const isRenameRenameConflict = (
  conflict: MergeConflict
): conflict is RenameRenameConflict => conflict.kind === 'rename/rename';

// One pole renamed a file while the other deleted it.
export type RenameDeleteConflict = {
  kind: 'rename/delete';
  artifactId: ResolvedArtifactId;
  basePath: string;
  renamedPath: string;
  deletedIn: MergePole;
};

export const isRenameDeleteConflict = (
  conflict: MergeConflict
): conflict is RenameDeleteConflict => conflict.kind === 'rename/delete';

// One pole renamed a file to a name that the other pole used for a new file.
export type RenameAddConflict = {
  kind: 'rename/add';
  renamedArtifactId: ResolvedArtifactId;
  basePath: string;
  renamedPath: string;
  addedArtifactId: ResolvedArtifactId;
  addedPath: string;
};

export const isRenameAddConflict = (
  conflict: MergeConflict
): conflict is RenameAddConflict => conflict.kind === 'rename/add';

// Both poles modified a submodule pointer to different commits.
export type SubmoduleConflict = {
  kind: 'submodule';
  path: string;
  targetCommit: Commit['id'];
  sourceCommit: Commit['id'];
};

export const isSubmoduleConflict = (
  conflict: MergeConflict
): conflict is SubmoduleConflict => conflict.kind === 'submodule';

export type CompareContentConflict = ContentConflict | AddAddConflict;

export const isCompareContentConflict = (
  conflict: MergeConflict
): conflict is CompareContentConflict =>
  isContentConflict(conflict) || isAddAddConflict(conflict);

export type StructuralConflict =
  | ModifyDeleteConflict
  | FileDirectoryConflict
  | RenameRenameConflict
  | RenameDeleteConflict
  | RenameAddConflict
  | SubmoduleConflict;

export const isStructuralConflict = (
  conflict: MergeConflict
): conflict is StructuralConflict =>
  isModifyDeleteConflict(conflict) ||
  isFileDirectoryConflict(conflict) ||
  isRenameRenameConflict(conflict) ||
  isRenameDeleteConflict(conflict) ||
  isRenameAddConflict(conflict) ||
  isSubmoduleConflict(conflict);

export type MergeConflict = CompareContentConflict | StructuralConflict;
