import { type Commit } from '../commit';
import { type ResolvedArtifactId } from '../resolved-artifact-id';
import { type MergePole } from './merge-poles';

// Unfortunately, there is no definitive list for these conflict types.
// The list was generated by an LLM and cross-checked with Git's source file:
// https://github.com/git/git/blob/9a2fb147f2c61d0cab52c883e7e26f5b7948e3ed/merge-ort.c

// Both poles modified the same file in conflicting ways.
export type ContentConflict = {
  kind: 'content';
  path: ResolvedArtifactId;
};

// One pole deleted a file while the other modified it.
export type ModifyDeleteConflict = {
  kind: 'modify/delete';
  path: ResolvedArtifactId;
  deletedIn: MergePole;
};

// Both poles added a file with the same name but different content.
export type AddAddConflict = {
  kind: 'add/add';
  path: ResolvedArtifactId;
};

// One pole added a file while the other added a directory with the same name.
export type FileDirectoryConflict = {
  kind: 'file/directory';
  filePath: ResolvedArtifactId;
  directoryPath: ResolvedArtifactId;
};

// Both poles renamed the same file to different names.
export type RenameRenameConflict = {
  kind: 'rename/rename';
  basePath: ResolvedArtifactId;
  targetPath: ResolvedArtifactId;
  sourcePath: ResolvedArtifactId;
};

// One pole renamed a file while the other deleted it.
export type RenameDeleteConflict = {
  kind: 'rename/delete';
  basePath: ResolvedArtifactId;
  renamedPath: ResolvedArtifactId;
  deletedIn: MergePole;
};

// One pole renamed a file to a name that the other pole used for a new file.
export type RenameAddConflict = {
  kind: 'rename/add';
  basePath: ResolvedArtifactId;
  renamedPath: ResolvedArtifactId;
  addedPath: ResolvedArtifactId;
};

// One pole has a directory where the other has a file with the same path.
export type DirectoryFileConflict = {
  kind: 'directory/file';
  directoryPath: ResolvedArtifactId;
  filePath: ResolvedArtifactId;
};

// Both poles modified a submodule pointer to different commits.
export type SubmoduleConflict = {
  kind: 'submodule';
  path: ResolvedArtifactId;
  targetCommit: Commit['id'];
  sourceCommit: Commit['id'];
};

export type MergeConflict =
  | ContentConflict
  | ModifyDeleteConflict
  | AddAddConflict
  | FileDirectoryConflict
  | RenameRenameConflict
  | RenameDeleteConflict
  | RenameAddConflict
  | DirectoryFileConflict
  | SubmoduleConflict;
