name: Setup PNPM
description: Configure pnpm to install dependencies and caching enabled
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v5
    - name: Setup Node.js with pnpm caching
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
