name: Setup PNPM
description: Configure pnpm to install dependencies and caching enabled
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Configure Node 20 with pnpm & caching setup
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
