name: On pull request
on:
  pull_request:
    branches:
      - main
jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Quality assuring submitted code
        uses: ./.github/actions/quality-checks
