name: On pull request
on:
  pull_request:
    branches:
      - main
jobs:
  quality-checks:
    runs-on: ubuntu-latest
    env:
      OKTANA_NPM_TOKEN: ${{ secrets.OKTANA_NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Quality assuring submitted code
        uses: ./.github/actions/quality-checks
