name: Quality Checks
description: Ensure code quality and consistency
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: 📦 Install dependencies
      shell: bash
      run: npm install
    - name: 🏗️ Compile & Build
      shell: bash
      run: npm run build
    - name: 🔎 Run ESLint checks
      shell: bash
      run: npm run lint
    - name: 🧪 Run tests
      shell: bash
      run: npm run test
