name: Quality Checks
description: Ensure code quality and consistency
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-pnpm
    - name: Execute all the Checks from the Makefile
      shell: bash
      run: make checks
